version: '3.8'

volumes:
  cache:
    driver: local

services:
  cache:
    image: redis:7.2-alpine3.19
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --user admin  --requirepass password
    volumes: 
      - cache:/data
